=== ArtistOfCode/code-generator/code-generator.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!ELEMENT config (settings,dataSource,javaModelGenerator,mapperGenerator,javaDaoGenerator,interfaceGenerator,serviceGenerator,controllerGenerator,table+)>
        <!ELEMENT settings (setting+)>
        <!ELEMENT setting (#PCDATA)>
        <!ELEMENT dataSource (#PCDATA)>
        <!ELEMENT javaModelGenerator (#PCDATA)>
        <!ELEMENT mapperGenerator (#PCDATA)>
        <!ELEMENT javaDaoGenerator (#PCDATA)>
        <!ELEMENT interfaceGenerator (#PCDATA)>
        <!ELEMENT serviceGenerator (#PCDATA)>
        <!ELEMENT controllerGenerator (#PCDATA)>
        <!ELEMENT table (#PCDATA)>

        <!ATTLIST setting name CDATA #REQUIRED>
        <!ATTLIST setting value CDATA #REQUIRED>

        <!ATTLIST dataSource driver CDATA #REQUIRED>
        <!ATTLIST dataSource url CDATA #REQUIRED>
        <!ATTLIST dataSource username CDATA #REQUIRED>
        <!ATTLIST dataSource password CDATA #REQUIRED>

        <!ATTLIST javaModelGenerator targetPackage CDATA #REQUIRED>
        <!ATTLIST javaModelGenerator targetProject CDATA #REQUIRED>

        <!ATTLIST mapperGenerator targetPackage CDATA #REQUIRED>
        <!ATTLIST mapperGenerator targetProject CDATA #REQUIRED>

        <!ATTLIST javaDaoGenerator targetPackage CDATA #REQUIRED>
        <!ATTLIST javaDaoGenerator targetProject CDATA #REQUIRED>

        <!ATTLIST interfaceGenerator targetPackage CDATA #REQUIRED>
        <!ATTLIST interfaceGenerator targetProject CDATA #REQUIRED>

        <!ATTLIST serviceGenerator targetPackage CDATA #REQUIRED>
        <!ATTLIST serviceGenerator targetProject CDATA #REQUIRED>

        <!ATTLIST controllerGenerator targetPackage CDATA #REQUIRED>
        <!ATTLIST controllerGenerator targetProject CDATA #REQUIRED>

        <!ATTLIST table className CDATA #REQUIRED>
        <!ATTLIST table tableName CDATA #REQUIRED>

=== ArtistOfCode/code-generator/generator-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "/AIJIANGNANLOVEHOUJUANJUAN/" "code-generator.dtd">

<config>
    <settings>
        <setting name="enableSerializable" value="true"/>
    </settings>
    <dataSource
            driver="com.mysql.jdbc.Driver"
            url="jdbc:mysql://47.104.148.155:3306/codeartist"
            username="root"
            password="root"
    />
    <javaModelGenerator
            targetPackage="com.codeartist.mybatis.disc.model"
            targetProject="./src/main/java"
    />
    <mapperGenerator
            targetPackage="com.codeartist.mybatis.disc.mapper"
            targetProject="./src/main/java"
    />
    <javaDaoGenerator
            targetPackage="com.codeartist.mybatis.disc.mapper"
            targetProject="./src/main/java"
    />
    <interfaceGenerator
            targetPackage="com.codeartist.mybatis.disc.mapper"
            targetProject="./src/main/java"
    />
    <serviceGenerator
            targetPackage="com.codeartist.mybatis.disc.mapper"
            targetProject="./src/main/java"
    />
    <controllerGenerator
            targetPackage="com.codeartist.mybatis.disc.mapper"
            targetProject="./src/main/java"
    />
    <table className="Admin" tableName="admin"/>
    <table className="" tableName="role"/>
</config>
